# Generated by Django 4.2.2 on 2023-06-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_auther_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tiltle',
            new_name='title',
        ),
    ]
